:PROPERTIES:
:ID:       a29f1a2c-0649-4029-8ac3-9bcc60c11102
:END:
#+title: paragliding

#+HUGO_SECTION: notes
#+filetags: diy paragliding
#+hugo_auto_set_lastmod: t
#+hugo_publishdate: 2025-04-26
#+HUGO_CUSTOM_FRONT_MATTER: :summary "Notes on paragliding, places, varios"
# #+hugo_categories: notes

* Certifications
** British Hang Gliding and Paragliding Association
The BHPA club system runs on a badge competency system. The first two [[https://en.wikipedia.org/wiki/British_Hang_Gliding_and_Paragliding_Association#Proficiency_levels][BHGP levels]].
- EP, Elementary Pilot badge
- CP – Club Pilot badge

With CP, the pilot can join a recreational club and fly outside of the school system, see more on [[https://www.bhpa.co.uk/safety/prs/][BHPA Pilot Rating Scheme(PRS)]] page.

Note: When taking a course through the BHPA certified school, the student must also sign up for a one-year membership of BHPA. As of 2025 the annual cost is £175. This seems to be due to third party insurance.

** International Pilot Proficiency Information, IPPI
The IPPI specifies five stages of paragliding proficiency, from the entry level SafePro Para 1 to 5. SafePro Delta is for hanggliding.
Note: There seems to be some renaming. =SafePro Para= was known as =ParaPro=

Many countries recognise the IPPI system. For e.g. Denmark and Germany the requirement is

- Minimum ratings are stage 4 for unsupervised flying and stage 5 for cross-country flights.

See the [[https://www.bhpa.co.uk/safety/overseas/#ippi][BHPA to IPPI conversion]]

* What to bring in a kit

Maybe get inspired from his medical kit
https://youtu.be/vZJ1icmiPHg?feature=shared

* Places
** Bir, Himachal Pradesh, India
[[https://www.paraglidingforum.com/viewtopic.php?p=88569#88569][(old) info for indepenent stayng in Bir]]

*** Getting there
The two closest international airports are Delhi and Amritsar.

There are many more flights to Delhi, so you”ll get cheaper deals if flying there, but Amritsar is closer to Bir, about six hours in a taxi or eight in a bus.
From Delhi you have more options:
- Quickest and most expensive is to fly to Dharamsala airport and take a taxi from there.
- There is a good overnight train from Delhi to Pathankot, which is about 4 hours by taxi from Bir, or for those of you who want to experience old-style India travel, you can then take a narrow-gauge railway line from Pathankot that stops at Ahju, which is just three km from Bir. It will take you eight hours, though! Trains can be booked on the Indian Railways website.
- There are overnight buses from Delhi too. Some go directly to Baijnath, which is half an hour from Bir, but there are many more plying the route to Manali and they all stop at Mandi, which is 2 hours from Bir.
*** Where to stay
[[https://www.colonelsresort.com/][Colonels Resort]]. Book well in advance. Tents should be ok.

*** Paragliding Season in Bir Billing

Generally Bir Billing remains open for paragliding from the mid of September to the 1st week of July. From July to August the valley remain closed due to heavy rainfall. Lots of tourists from the other countries and various parts of the country usually come here in two different period of time for paragliding:

The best timing for paragliding starts from The 1st week of October till the Mid of December. The months of October and November are the best time for paragliding. During this period the wind remains clam and little warm almost every day which is good for normal flight. The paragliding competitions use to happen during this time.

The second best period for paragliding starts from the beginning of March till June. This period is the longest season for paragliding in Bir Billing and good for cross country flying as you get lots of thermal. But the wind is quite strong during the day and thunderstorms may be frequent during this time.

From the mid of December, January till the mid of February are valid for paragliding, but flight remain low as the cool air temperature does not encourage the para-glider to fly high or for longer duration.
** Aguergour, Atlas mountains, Morocco


[[https://maps.app.goo.gl/S9yd2zbJ1gLJocE76][Gite Aznag]] owned by Naima (WHatsApp:[[https://wa.me/+212660947872][+212660947872]]).

Awesome place, simple life, possible to top-land. Strong thermals.

* Varios
** Airspace awareness / collision avoidance
*** FLARM (Flight Alarm)
A collision-avoidance system developed primarily for gliders, light aircraft and helicopters in the alps.

How it works:
- Transmits the aircraft's GPS position, altitude, and velocity.
- Receives similar data from nearby FLARM-equipped aircraft.

FLARM is proprietary.

*** FANET (Flying Ad-hoc Network)
A mesh network communication system developed specifically for paragliders and hang gliders.

How it works:
- Shares GPS position data among nearby FANET devices.
- Supports live tracking and airspace awareness between paragliders.

Not visible to sailplanes or helicopters unless those also have FANET, which is rare.

*** stand-alone devices
**** LilyGo T-Echo
The [[https://lilygo.cc/products/t-echo-lilygo][LilyGo T-Echo]] is a standalone open-source device that can be configured to transmit and receive FLARM, FANET+ protocols.

Depending on the installed firmware
- Meshtastic: Off-grid, text-based messaging over LoRa, could be useful for Hikers, backcountry skiers, disaster preppers.
- SoftRF: for Aviation, Broadcast and receive aircraft positions (FLARM/FANET/OGN).

T-Echo can be used with a non-gps, non-FLARM vario to get the same functionality as full fledged FLARM vario but at a much lower price.
** XC Tracer Mini V
The [[https://www.xctracer.com/en/xctracerminiiiigps][Mini V]] is often recommended.
- Accelerometer/Compass/Gyro/Baro/GPS/BLE/FLARM/FANET
- Solar cell
This is an "instant vario", meaning that it fuses the data from 9dof sensors (accelerometer, gyro, pressure) with Kalman filtering.

It combines everything, but cost around 500€
** BlueBip
The [[https://www.stodeus.com/shop/en/][BlueBip]] is a bluetooth Vario (around 200€). It does not have GPS or FLARM, but combined with [[*LilyGo T-Echo]] it is a full-fledged alternative to XC Tracer Mini, but 200€ cheaper.
It does have LEDs for visual vario which some [[https://www.paraglidingforum.com/viewtopic.php?p=p686003#p686003][like]].
** MipBip+
The [[https://shop.mipfly.com/index.php?route=product/product&product_id=81][MipBip+]] (95€) is probably the cheapest instant variometer.

** DIY
*** ESP32C3 based
The [[https://pataga.net.in/pataga/varios.html][author has a page with notes on DIY varios]]

[[https://github.com/har-in-air/ESP32C3_BLUETOOTH_AUDIO_VARIO][ESP32C3 BLE audio Vario]] is a instant vario, fusing accelerometer and pressure data using Kalman filtering.

It uses a CJMCU-117 module for data
- MS5611: High-resolution barometric pressure sensor (altimeter)
- MPU-9250 (discontinued): 9-axis IMU: 3-axis gyroscope, 3-axis accelerometer, 3-axis magnetometer

An IMU measures motion and orientation using a combination of sensors:
| Sensor Type   | Measures                                      |
|---------------+-----------------------------------------------|
| Accelerometer | Linear acceleration (e.g., gravity, G-forces) |
| Gyroscope     | Angular velocity (how fast you're rotating)   |
| Magnetometer  | Magnetic field (like a compass) — optional    |

[[https://www.reddit.com/r/AskElectronics/comments/ebbhgo/a_decent_replacement_for_the_mpu9250][The icm20948 is the official replacement of the mpu9250]], but as of 2024 the ICM-20948 is not recommended for new designs as the magnetometer used is no longer manufactured.

The pcb + lipo cell is made to fit with inside a [[https://www.hammfg.com/electronics/small-case/plastic/1551][Hammond 1551K]] (80,40,20)mm enclosure. (length, width, depth(including lid). The walls are 2mm thick)
There is a [[https://www.thingiverse.com/thing:1695285][3d scad version]] of a Hammond box.

https://www.pjrc.com/store/prop_shield.html
https://github.com/PaulStoffregen/NXPMotionSense/
https://github.com/PaulStoffregen/MotionCal
https://github.com/PaulStoffregen/MotionCal/issues/8
#+begin_quote
        change the data type of the raw sensor data to int,

         lsm.read();

// Print the sensor data
Serial.print("Raw:");
Serial.print((int)lsm.accelData.x);
Serial.print(',');
Serial.print((int)lsm.accelData.y);
Serial.print(',');
Serial.print((int)lsm.accelData.z);
Serial.print(',');
Serial.print((int)lsm.gyroData.x);
Serial.print(',');
Serial.print((int)lsm.gyroData.y);
Serial.print(',');
Serial.print((int)lsm.gyroData.z);
Serial.print(',');
Serial.print((int)lsm.magData.x);
Serial.print(',');
Serial.print((int)lsm.magData.y);
Serial.print(',');
Serial.print((int)lsm.magData.z);
Serial.println(); `
#+end_quote
https://forum.pjrc.com/threads/59277-Motion-Sensor-Calibration-Tool-Parameter-Understanding

*** Android phone with XCVario App
[[https://play.google.com/store/apps/details?id=org.theflightvario.simplevario.xc][XCVario App]] can be used on a phone with internal barometer, like googles pixel phones.

See this [[https://youtu.be/5eLnei9-yFw][video]] for a comparison between the app and a XCTracer. The app performs just as well.
