:PROPERTIES:
:ID:       15924c21-a2f1-4ac3-8fb6-dbf2f2935583
:END:
#+title: android

* Rooting

** unlock bootloader / enter fastboot

 Be aware that changing the lock state will do a factory reset
#+begin_src sh
adb reboot bootloader

fastboot devices
fastboot flashing unlock
# fastboot flashing lock
# fastboot reboot
#+end_src

** A/B slots

fastboot
#+begin_src sh
adb reboot bootlader
fastboot --set-active=[a|b]
fastboot reboot
#+end_src

or fastbootD
#+begin_src sh
adb reboot fastboot
fastboot getvar current-slot
fastboot set_active b
#+end_src

Dynamic partitions are only supposed to be flashed in fastbootd, as opposed to the bootloader fastboot. To get to fastbootd from the bootloader fastboot, run:
: fastboot reboot fastboot

*** reset boot counter
Upgrade roll-back is implemented using a counter, it is initialised at 7 and decremented every time you boot the system unless you set the "boot successful" flag from userspace. When the counter reaches 0 the bootloader will automatically mark the slot as "unbootable" and switch to the other slot.

If you device randomly got stuck in fastboot after a reboot, that means the counter hit zero and the bootloader marked your slot as unbootable.

You can fix this quite easily, first get the current slot:
#+begin_src sh
adb reboot fastboot
fastboot getvar current-slot
#+end_src
If the current slot is =a=, run the following to reset the flags:
#+begin_src sh
fastboot set_active b
fastboot set_active a
#+end_src
** Key combos
Key combos:

    POWER + VOL UP = recovery/fastbootd
    POWER + VOL UP + VOL DOWN = bootloader/normal fastboot\
    VOL+UP+VOL DOWN + INSERT CABLE = edl mode (If an MSM tool ever gets released)
** Play integrity api/ Safety levels

Play integrity api is made by google to check if your device integrity is fine for "security reasons".
It have 3 (4) level:
1. Basic integrity. Software based, does pass on almost every rom.
2. Device integrity: fingerprint based BUT if your device support strong integrity it will use that. Device integrity can be passed by using "play integrity fix"(pif), but some rom need to be updated to pass it (or need root and install it)
3. Strong integrity: hardware based check, cant be bypassed. Need to hide the unlocked bootloader as well

Google Wallet use PI api and the phone has to pass device integrity, for the app to work.
** Hide magisk
Info about Play Integrity API
https://xdaforums.com/t/info-play-integrity-api-replacement-for-safetynet.4479337/

Install this app: https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck and run test.

To use Google Wallet you must pass BASIC and DEVICE verdicts. If you don't pass BASIC, something is wrong in your setup, DroidGuard is detecting root or injection.
If you pass BASIC but don't pass DEVICE you have two options:

1.
https://github.com/chiteroman/PlayIntegrityFix
https://xdaforums.com/t/module-play-integrity-fix-safetynet-fix.4607985/

With automatic pull a working fingerprint when the previous one gets banned.
https://github.com/daboynb/PlayIntegrityNEXT

2.
Use SafetyNet fix, but soon deprecated.
** Magisk Modules
https://xdaforums.com/t/module-detach3-detach-market-links.3447494/
** fastboot vs fastbootD
Since Android 10, Android has created the "dynamic partitions", which allows the ROM/OS to choose the size for the system, vendor and product partitions, as they are "logical partitions" on the single super partition.

Normal fastboot, with no access to userspace, cannot work with these dynamic partitions and can only deal with the actual partition (the super partition). To work with the dynamic partitions through a fastboot-like interface, "fastbootd" was created.

Unlike the actual fastboot which is in the firmware, fastbootd is completely handled by the recovery/located in userspace, and can be accessed by "fastboot reboot fastboot" in normal fastboot mode.

[[https://wiki.postmarketos.org/wiki/Android_dynamic_partitions]]
*** restart into

fastboot
#+begin_src sh
adb reboot bootloader
#+end_src

fastbootD
#+begin_src sh
adb reboot fastboot

# or from fastboot
fastboot reboot fastboot
#+end_src
* Apps
** ReVanced
[[https://www.reddit.com/r/revancedapp/comments/159zbb6/guide_youtube_revanced/][guide]]

** Call Recorders (require root)

Paid
https://callrecorder.skvalex.com/get

Free
https://github.com/chenxiaolong/BCR
** Split APKM to APK
https://maximoff.su/apktool/
