# -*- ispell-local-dictionary: "da" -*-
:PROPERTIES:
:ID:       9ec5ffb5-3c37-4ffc-9f37-062b75d2b6ca
# :link-img:   ../.attach/tafraout-2025/boulder*.jpg
:END:
#+title: Big in Japan

#+HUGO_SECTION: post
#+filetags: skiing climbing traveling
#+hugo_categories: traveling
#+hugo_auto_set_lastmod: t
#+hugo_publishdate: 2023-04-26
#+hugo_bundle: japan-2022
#+export_file_name: index

I spent three months on Hokkaido, the northern most island in Japan. I quit my job, this was my story to my colleagues

#+hugo: more


* Indledning
Kære magenta-folk.

Her er en sidste fortælling fra mig, fra et ansvarsfrit liv uden arbejde i Japan.

Jeg var på øen Hokkaido i tre måneder. Turister kommer her om vinteren for at stå på ski, for i løbet af januar og februar sner det næsten hver dag. Jeg har aldrig set så megen sne før.

Jeg har en tjekkisk kammerat jeg kender fra klatring. Han ringede i november og spurgte om jeg ville med til Japan og hjælpe ham med sit ski guide-firma i skisæsonen, der strækker sig over januar og februar. Han lejer et større hus i byen Kutchan hvor der ellers kun bor japanere, får besøg af 12 klienter 10 dage ad gangen der bor i huset. Hver morgen kl 08 bliver de læsset i vans og kørt rundt til hvor der er nyt sne. Jeg fulgte i hælene på dem, lånte udstyr og tog med ud for at stå på ski, mod at jeg lavede morgenmad (og en masse andet, skulle det vise sig). Jeg stod op klokken 05.30 hver dag for at lave morgenmad.

* Mt. Yotei og lavinen
Min første tur op af Mt Yotei, den lokale vulkan der er dækket af sne og næsten perfekt kegle-formet - dvs vi kan gå med ski til randen (gå fra 300m til 1800m) var en oplevelse. Efter trægrænsen føles det som en isørken. Vinden har blæst al sne af blotlagte flader, så der kun er et islag tilbage og de klipper der stikker op hist og her er indkapslet i is.

Det var den første uge i januar med den første gruppe, så min kammerat og guide på turen ville gerne sikre at alle havde en god oplevelse. Det er svært at stå på ski på islagte skråninger, så på vej ned søgte han væk fra de sikre blotlagte skråninger og vi endte på højre indvendige side af en kløft.

Der var en klient der kørte ned af siden, krydsede bunden og lavede et sving på den modsatte side af kløften. Desværre var det læsiden, og vinden havde deponeret en masse sne. Så da hun lavede sit sving, satte hun gang i en lavine, blev fanget af den og transporteret ned i bunden af kløften og derefter 400m videre ned gennem kløften. Vi fandt hende hurtigt, jeg tror hun var begravet mellem 5-10 min og guiden havde gravet hendes ansigt frit da jeg kom.

Jeg tænkte hun var død, gravede hende helt fri og hun fik CPR i 45 min indtil en helikopter kom. Obduktionsrapporten viser at hun døde af kvælning, så jeg spekulerer lidt på om vi havde hendes hoved bøjet langt nok tilbage ved kunstigt åndedræt. Der kom ildelugtende luft ud af hende efter visse pust, hvilket jeg har fået at vide tyder på at luften havnede i maven.

Fordi det var en guidet tur, og jeg er ven med guiden blev vi afhørt af politiet. Jeg havde tre dage, 09-16 i et lille firkantet lokale uden vinduer. Det mindede mig lidt om gamle britiske tv-krimier som Columbo. Politiet var venlige, de undersøger om guiden kan sigtes for "professional misconduct", ie. var det uansvarligt af ham at tage en gruppe med op af Yotei den dag. Det var det måske, for vejret var varmt og det blæste meget og måske tog vi ukendte risici i jagten på god sne, men det er også nemt at være bagklog. Politiet er utroligt grundige, efterforskningen er stadig i gang, ulykken skete d. 13 januar.

Det var selvfølgelig trist men jeg kendte hende ikke personligt, så jeg ser det mere som en dyr lærestreg. Jeg kunne lige så godt have kørt på ski der hvor hun lavede et sving og satte lavinen i gang. Huset har kun en hukommelse på gruppernes ophold, så da gruppen involveret i lavinen tog hjem, var det som om ulykken var sket i en anden tid.

\#+CAPTION: Begravet under 1.5 m sne. Her bliver hun hentet af helikopteren.
\[\[file\:IMG\_20230113\_152136.jpg]]

Der var oprindeligt to guider på turen; den ene vendte om tidligt og var ikke med på toppen, og da lavinen ramte. Han blev plaget af skyldfølelse og det satte gang i en mental deroute (tror jeg). Han blev så dårlig at han intet kunne, fik antidepressive piller og måtte hentes hjem af sin kone og blev indlagt på et psykiatrisk hospital. En slovakisk UIAGM guide der for under et år siden var to gange på toppen af Denali (højeste bjerg i Nordamerika). Vi snakkede en del sammen efter hans deroute (de andre tjekkiske "staff" behandlede ham ret dårligt (som et barn)), og det var trist at se ham forvandlet til en opgivende skal. I dag er han heldigvis bedre og jeg håber han får håndteret sine problemer. Jeg glæder mig til at besøge ham i Slovakiet på et tidspunkt.

\#+CAPTION: Toppen af Mt Yotei igen. Total whiteout.
\[\[file\:WhatsApp\_Image\_2023-03-09\_at\_04.22.52.jpeg]]

\#+CAPTION: Mt Yotei i baggrunden ("mini Mt Fuji").
\[\[file\:yotei.JPG]]

* Skitouring og forår
Jeg har lært en hel del om skitouring, så det er ret godt. Sæsonen er slut, det er gået fra pulversne til forår, alle guides og klienter tog hjem og jeg havde huset for mig selv den sidste måned. Her er jeg med nogle japanere jeg mødte tilfældigt mens jeg var ude for at "toure". Sneen er dyb. Uden ski ville jeg synke i til hoften.

\[\[file\:WhatsApp\_Image.jpeg]]

Jeg tager nogle forårsturer alene. Sneen er stabil, solen skinner og jeg ville lave en travers fra Niseko til det japanske hav. En travers betyder her at krydse alle bjerge/toppe på min vej. En slags haute route i Japan.

[[https://hokkaidowilds.org/ski-touring/niseko-haute-route][Niseko Haute Route]]

\[\[file\:traversing-annupuri-16-map.jpg]]

Undervejs fik jeg den ide at jeg sikkert også kunne gå tilbage igen. Jeg havde en pandelampe, så jeg tænkte det nok skulle gå. Min makker var glad da vi nåede havet og tog bussen tilbage.

\#+CAPTION: Sidste top inden det begynder at gå nedad mod havet.
\[\[file:336062756\_736925784705630\_7177154585889314445\_n.jpg]]

\#+CAPTION: 300 m højde – sneen sluttede og vi måtte gå.
\[\[file:336153493\_209434198370631\_7279002004949428175\_n.jpg]]

Jeg havde sat kl 13 som seneste tidspunkt til at starte tilbageturen. Men vi var forsinket og jeg kom først fra stranden kl 16.

\[\[file:336158949\_1187110445155943\_7888453275509253099\_n.jpg]]

Den første top på tilbageturen kan lige ses i baggrunden. Der var 2000 m højdeforskel og som jeg nåede toppen gik solen ned.

\[\[file\:DSC\_0078.JPG]]

Solen på vej ned over havet. Det gik op for mig at der stadig var ret langt hjem. Jeg har nogle "skins" klæbet under skiene så jeg kan gå opad. Når solen skinner, smelter lidt af sneen og skins'ne bliver våde. Da solen gik ned og det blev koldt, holdt limen op med at klæbe pga. fugten så jeg tapede dem fast. Det betød at skiene ikke rigtig gled og jeg måtte løfte dem ved hvert skridt. Det lærte jeg noget af. Fx, det er surt når ens skins falder af - og tape ødelægger evnen til at glide.

Jeg lærte også at det ikke var helt så romantisk og hyggeligt som jeg havde forestillet mig, dels fordi månen ikke var fremme og det blæste. Det var aldrig farligt, mere ukomfortabelt og jeg var ret glad da jeg nåede frem til bilen ved midnat. Vi forlod bilen 05.40.

\[\[file:336257236\_770401457976116\_7999993091903877652\_n.jpg]]

* Bilen og små eventyr
Her er min bil. En dødsfælde. Den har airbag, hvilket fik mig til at smile. Så hvis jeg kører ind i noget brækker jeg nok ikke næsen. Til gengæld bliver mine ben klippet af. Jeg havde lejet den af en der er kendt af de lokale som Dodgy Yoshi.

\[\[file\:WhatsApp\_Image\_2023-03-09\_at\_04.14.46.jpeg]]

Min første blaffer, samme dag jeg fik bilen. Eller han ville tage bussen og jeg spurgte om han ikke hellere ville med mig. Japansk mand på 87 år.

\[\[file\:DSC\_0001.JPG]]

Bilen havde et dårligt batteri. En dag kom jeg tilbage til bilen, med våde sokker og egentlig bare gerne ville hjem, og så at højre styrepind stadig stod på "lys tændt", var jeg klar over at batteriet var fladt.

Jeg prøvede først at skubbe rundt med bilen alene, få den lidt i fart, hoppe ind, sætte den i 2. gear og se om den ville starte. Men jeg kunne ikke skubbe den hurtigt nok. Heldigvis kom der først en lastbil og dernæst en motorcykel ind hvor jeg holdt. Jeg fik dem til at hjælpe med at skubbe (jeg stillede mig foran deres køretøjer, så de var klar over at der ikke var anden mulighed... :)). Men der var stadig ikke nok fart i bilen.

Så fik vi den ide at lastbilen kunne trække den i gang. Jeg holdt ved havet, og efter et par minutters søgen på stranden fandt jeg et reb. Desværre var det stadig ikke muligt at trække bilen i gang, vi tog ellers et par omgange.

\[\[file\:WhatsApp\_Image\_2023-03-28\_at\_02.22.53.jpeg]]
\[\[file\:WhatsApp\_Image\_2023-03-28\_at\_02.22.53(1).jpeg]]

Jeg tænkte batteriet var fuldstændig drænet, bilen havde brug for lidt strøm og kunne se at vi ikke ville få den startet. Mine hjælpere forsvandt ret hurtigt, men heldigvis kom endnu en lastbil. Han havde heller ikke startkabler men indvilligede i at køre mig til nærmeste by (8 km), hvor vi fandt en mekaniker. Han ville have nogle penge for at hjælpe mig, men det var ikke noget problem. For jeg vidste at jeg havde 30.000 yen (1500 dkk) i kontanter. Desværre var de ikke i min pung og da jeg smilende åbnede den og sagde intet problem, grinede de da de så jeg havde hvad svarer til 50 kr.

Heldigvis har de humor og det er bedre at grine af absurde situationer. Nå, jeg hiver lidt i hans ærme, nogle andre blander sig og til sidst peger han på sin bil, jeg hopper ind og vi kører tilbage til min. Det tager et øjeblik, kablerne er forbundet og min bil starter. Således kører jeg smilende hjem. Med våde tæer, lidt forundret over det ikke lykkedes at trække bilen i gang og spændt på hvor mange gange jeg vil glemme at slukke for lyset (tre gange. Rimelig dumt).

\[\[file\:WhatsApp\_Image\_2023-03-28\_at\_02.26.56.jpeg]]

Sidst, en video af mig der prøver at køre over en "pillow" (busk dækket af sne) for første gang. Tilbage i januar, totalt begynder.

\#+CAPTION: Video (WhatsApp 2023-03-10).
\[\[file\:WhatsApp\_Video\_2023-03-10\_at\_03.04.00.mp4]]
\#+CAPTION: Video (17. marts 2023).
\[\[file\:VIDEO-2023-03-17-08-09-11.mp4]]

* Tilbage i Danmark
Jeg er nu tilbage i Danmark.

Jeg har fået eftergivet hele min gæld på 250.000 dkk af DFIM. Det startede med en artikel i TV2 Syd om en mand der havde haft en gammel motorcykel i laden og nu skyldte ca 250.000. Artiklen fik nogle politikere til at kommentere på sagen, der kom yderligere nogle artikler og manden endte med at få eftergivet sin gæld.

Jeg ringede til DFIM og ville have samme ordning. Det blev til at jeg skulle dokumentere at jeg var i Belgien da loven trådte i kraft, jeg skilte motorcykel totalt ad og sendte dem billederne inden jeg tog til Japan. En måned efter fik jeg at vide at min gæld også var eftergivet. De fleste andre har fået deres gæld reduceret til en ny maksgrænse på 25.000 dkk.

Jeg har spurgt mange om hvad jeg skulle gøre. DFM sagde afdragsordning. Morten er den eneste der sagde jeg ikke skulle erklære mig skyldig. Det gjorde jeg selvfølgelig ikke og det er så endt med jeg ikke skal betale. Men jeg er stadig forundret over at man bare kan få en indkaldelse på 250.000 til fogedretten, som en popup i e-boks, uden at nogen myndighedsperson tænker der er sket en fejl. Først når journalister tager sagen op, sker der noget.

Jeg er nu i Danmark. Jeg har søgt et arbejde. Hvis jeg får det, skal jeg spare nogle penge op og flytte til et land uden e-boks og med bjerge.

Jeg håber I får en rigtig god sommer. Jeg tager til Sverige, til fødselsdag for Göteborgs klippe-klatreklub på fredag.

Mange hilsner,
Paw

* PS
Den første gruppe i Japan lavede en video med mig.

* Metadata / Importnote
Denne fil er konverteret fra en multipart e-mail til Org-mode. Vedhæftede billeder og videoer refereres som lokale filer med deres oprindelige (let normaliserede) filnavne. Sørg for at placere filerne i samme mappe som denne *.org* fil for at få inline-visning i Emacs (se =org-display-inline-images=).
